version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.4

jobs:

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
            poetry install
      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
          key: v1-dependencies-{{ checksum "poetry.lock" }}
      - run:
          name: Check coding style
          command: |
            poetry run flake8 kbench

  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: >
            poetry publish --build --no-interaction
            --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}"

workflows:
  version: 2

  build-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
