version: 2

jobs:

  test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            poetry install
      - run:
          name: Check coding style
          command: |
            poetry run flake8 kbench

  publish:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: >
            poetry publish --build --no-interaction
            --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}"

  e2e:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Install kind
          command: |
            curl -L -o kind https://github.com/kubernetes-sigs/kind/releases/download/v0.4.0/kind-linux-amd64
            sudo install -o root -g root -m 0755 kind /usr/local/bin/kind
      - run:
          name: Create Kubernetes cluster
          command: kind create cluster
      - run:
          name: Install dependencies
          command: |
            pip3 install poetry
            poetry install
      - run:
          name: Test pod-latency benchmark
          command: |
            KUBECONFIG="$(kind get kubeconfig-path --name="kind")" poetry run python3 -m kbench -v pod-latency -n 3
      - run:
          name: Test pod-throughput benchmark
          command: |
            KUBECONFIG="$(kind get kubeconfig-path --name="kind")" poetry run python3 -m kbench -v pod-throughput -n 3
      - run:
          name: Test deployment-scaling benchmark
          command: |
            KUBECONFIG="$(kind get kubeconfig-path --name="kind")" poetry run python3 -m kbench -v deployment-scaling -m 2 -n 3

workflows:
  version: 2

  build-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
      - e2e:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - test
            - e2e
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
